# experiment name
note: train

#project basic
task: motionVqvae  # interVAE reconstruction

#model basic
gpu_index: 0
lr: 0.0002
batchsize: 64
frame_length: 16
epoch: 50
worker: 4
use_sch: True
model_type: smpl

#********dataset*********#
# The path for datasets and annotations
data_folder: data/dataset
output: output

trainset: Hi4D
testset: Hi4D

# cliff hmr cliff_hmr pose_transformer_v8  relation relation_v8
model: MotionVQVAE #interhuman_diffusion_phys
use_prior: False

mode: train # train/test/eval


# Use pretrain model and the corresponding path
pretrain: False
pretrain_dir: data/checkpoint.pkl


# The name of your training loss function
# Split different names with a single space
# e.g., KL_Loss MPJPE L1 L2
train_loss: VQVAE_Loss # SMPL_Loss Keyp_Loss Mesh_Loss Joint_Loss Pen_Loss Vel_Loss
test_loss: MPJPE_instance #MPJPE #MPJPE PCK PA_MPJPE MPJPE_H36M MPJPE_instance Interaction

#visualize
viz: False
